=head1 NAME

 Imgur::API::Endpoint::Custom_gallery

=head1 DESCRIPTION

 Access to the imgur Custom_gallery API Endpoint. 

 See: https://api.imgur.com/endpoints/custom_gallery

=cut

=head1 METHODS
 
=head2 customGallery

 View images for current user's custom gallery

B<Parameters>

=item *
 C<window> I<optional>

 Change the date range of the request if the sort is "top", day | week | month | year | all, defaults to week

=item *
 C<page> I<optional>

 integer - the data paging number

=item *
 C<sort> I<optional>

 viral | time | top - defaults to viral

=cut

=head2 customGalleryImage

 View a single image in a user's custom gallery

B<Parameters>

=item *
 C<image_id> I<required>

 The ID for the gallery item.

=item *
 C<item_id> I<required>

 Item_id

=cut

=head2 customGalleryAdd

 Add tags to a user's custom gallery

B<Parameters>

=item *
 C<tags> I<required>

 Array of tags (e.g. 'cats,dogs')

=cut

=head2 customGalleryRemove

 Remove tags from a custom gallery

B<Parameters>

=item *
 C<tags> I<required>

 Array of tags (e.g. 'cats,dogs')

=cut


