=head1 NAME

 Imgur::API::Endpoint::Gallery

=head1 SYNOPSISA

 Access to the imgur Gallery API Endpoint. 

 See: https://api.imgur.com/endpoints/gallery

=cut

=head1 METHODS
 
=head2 get(%params)

 Returns the images in the gallery. For example the main gallery is https://api.imgur.com/3/gallery/hot/viral/0.json

=head3 Parameters
=over 4

=item *
showViral OPTIONAL
 true | false - Show or hide viral images from the 'user' section. Defaults to true

=item *
section OPTIONAL
 hot | top | user - defaults to hot

=item *
window OPTIONAL
 Change the date range of the request if the section is "top", day | week | month | year | all, defaults to day

=item *
page OPTIONAL
 integer - the data paging number

=item *
sort OPTIONAL
 viral | top | time | rising (only available with user section) - defaults to viral

=back
=cut

=head2 memeSubgallery(%params)

 View images for memes subgallery

=head3 Parameters
=over 4

=item *
window OPTIONAL
 Change the date range of the request if the sort is "top", day | week | month | year | all, defaults to week

=item *
page OPTIONAL
 integer - the data paging number

=item *
sort OPTIONAL
 viral | time | top - defaults to viral

=back
=cut

=head2 memeSubgalleryImage(%params)

 View a single image in the memes gallery

=head3 Parameters
=over 4

=item *
image_id REQUIRED
 The ID for the image.

=back
=cut

=head2 subreddit(%params)

 View gallery images for a subreddit

=head3 Parameters
=over 4

=item *
page OPTIONAL
 integer - the data paging number

=item *
window OPTIONAL
 Change the date range of the request if the sort is "top", day | week | month | year | all, defaults to week

=item *
sort OPTIONAL
 time | top - defaults to time

=item *
subreddit REQUIRED
 pics - A valid subreddit name

=back
=cut

=head2 subredditImage(%params)

 View a single image in the subreddit

=head3 Parameters
=over 4

=item *
image_id REQUIRED
 The ID for the image.

=item *
subreddit REQUIRED
 pics - A valid subreddit name

=back
=cut

=head2 tag(%params)

 View images for a gallery tag

=head3 Parameters
=over 4

=item *
sort OPTIONAL
 viral | time | top - defaults to viral

=item *
page OPTIONAL
 integer - the data paging number

=item *
window OPTIONAL
 Change the date range of the request if the sort is "top", day | week | month | year | all, defaults to week

=item *
t_name REQUIRED
 The name of the tag.

=back
=cut

=head2 tagImage(%params)

 View a single image in a gallery tag

=head3 Parameters
=over 4

=item *
t_name REQUIRED
 The name of the tag.

=item *
image_id REQUIRED
 The ID for the image.

=back
=cut

=head2 itemTags(%params)

 View tags for a gallery item

=head3 Parameters
=over 4

=item *
id REQUIRED
 ID of the gallery item

=item *
gallery REQUIRED
 Gallery

=back
=cut

=head2 tagVote(%params)

 Vote for a tag, 'up' or 'down' vote. Send the same value again to undo a vote.

=head3 Parameters
=over 4

=item *
gallery REQUIRED
 Gallery

=item *
id REQUIRED
 ID of the gallery item

=item *
t_name REQUIRED
 Name of the tag (implicitly created, if doesn't exist)

=item *
vote REQUIRED
 'up' or 'down'

=back
=cut

=head2 updateGalleryTags(%params)

 Update the tags for a post in the gallery

=head3 Parameters
=over 4

=item *
gallery REQUIRED
 Gallery

=item *
id REQUIRED
 ID of the gallery item

=item *
tags REQUIRED
 The name of the tags you wish to associate with a post. Can be passed as tags[]=funny&tags[]=cat or tags=funny,cat/td>
                    

=back
=cut

=head2 search(%params)

 Search the gallery with a given query string.

=head3 Parameters
=over 4

=item *
sort OPTIONAL
 time | viral | top - defaults to time

=item *
window OPTIONAL
 Change the date range of the request if the sort is 'top', day | week | month | year | all, defaults to all.

=item *
page OPTIONAL
 integer - the data paging number

=back
=cut

=head2 random(%params)

 Returns a random set of gallery images.

=head3 Parameters
=over 4

=item *
page OPTIONAL
 A page of random gallery images, from 0-50. Pages are regenerated every hour.

=back
=cut

=head2 toGallery(%params)

 Share an Album or Image to the Gallery.

=head3 Parameters
=over 4

=item *
title REQUIRED
 The title of the image. This is required.

=item *
terms OPTIONAL
 If the user has not accepted our terms yet, this endpoint will return an error. To by-pass the terms in general simply set this value to 1.

=item *
gallery REQUIRED
 Gallery

=item *
topic OPTIONAL
 Topic name

=item *
mature OPTIONAL
 If the post is mature, set this value to 1.

=item *
tags[] OPTIONAL
 The name of the tags you wish to associate with a post. Can be passed as tags[]=funny&tags[]=cat or tags=funny,cat

=back
=cut

=head2 fromGallery(%params)

 Remove an image from the gallery. You must be logged in as the owner of the item to do this action.

=head3 Parameters
=over 4

=item *
gallery REQUIRED
 Gallery

=back
=cut

=head2 album(%params)

 Get additional information about an album in the gallery.

=head3 Parameters
=over 4

=item *
gallery REQUIRED
 Gallery

=back
=cut

=head2 image(%params)

 Get additional information about an image in the gallery.

=head3 Parameters
=over 4

=item *
gallery REQUIRED
 Gallery

=back
=cut

=head2 reporting(%params)

 Report an Image in the gallery

=head3 Parameters
=over 4

=item *
2 REQUIRED
 

=item *
4 REQUIRED
 

=item *
1 REQUIRED
 

=item *
3 REQUIRED
 

=item *
reason OPTIONAL
 An integer representing the reason for the report
                            Value
                                    Description
                                1
                                    Doesn't belong on Imgur
                                2
                                    Spam
                                3
                                    Abusive
                                4
                                    Mature content not marked as mature
                                5
                                    Pornography
                                

=item *
5 REQUIRED
 

=back
=cut

=head2 votes(%params)

 Get the vote information about an image

=head3 Parameters
=over 4

=item *
gallery REQUIRED
 Gallery

=back
=cut

=head2 voting(%params)

 Vote for an image, 'up' or 'down' vote. Send 'veto' to undo a vote.

=head3 Parameters
=over 4

=item *
vote REQUIRED
 Vote

=item *
gallery REQUIRED
 Gallery

=back
=cut

=head2 comments(%params)

 Comment on an image in the gallery.

=head3 Parameters
=over 4

=item *
sort OPTIONAL
 best | top | new - defaults to best 

=item *
gallery REQUIRED
 Gallery

=back
=cut

=head2 comment(%params)

 Information about a specific comment. This action also allows any of the additional actions provided in the Comment Endpoint.

=head3 Parameters
=over 4

=item *
comment REQUIRED
 Comment

=item *
gallery REQUIRED
 Gallery

=back
=cut

=head2 commentCreation(%params)

 Create a comment for an image.

=head3 Parameters
=over 4

=item *
comment REQUIRED
 The text of the comment.

=item *
gallery REQUIRED
 Gallery

=back
=cut

=head2 commentReply(%params)

 Reply to a comment that has been created for an image.

=head3 Parameters
=over 4

=item *
commentReply REQUIRED
 CommentReply

=item *
gallery REQUIRED
 Gallery

=item *
comment REQUIRED
 The text you want to use as the reply.

=back
=cut

=head2 commentIds(%params)

 List all of the IDs for the comments on an image.

=head3 Parameters
=over 4

=item *
gallery REQUIRED
 Gallery

=back
=cut

=head2 commentCount(%params)

 The number of comments on an Image.

=head3 Parameters
=over 4

=item *
gallery REQUIRED
 Gallery

=back
=cut


