=head1 NAME

 Imgur::API::Endpoint::Image

=head1 DESCRIPTION

 Access to the imgur Image API Endpoint. 

 See: https://api.imgur.com/endpoints/image

=cut

=head1 METHODS
 
=head2 get

 Get information about an image.

B<Parameters>

=item *
 C<image> I<required>

 Image

=cut

=head2 upload

 Upload a new image.

B<Parameters>

=item *
 C<title> I<optional>

 The title of the image.

=item *
 C<album> I<optional>

 
                    The id of the album you want to add the image to.
                    For anonymous albums, {album} should be the
                    deletehash that is returned at creation.
                

=item *
 C<description> I<optional>

 The description of the image.

=item *
 C<image> I<required>

 A binary file, base64 data, or a URL for an image. (up to 10MB)

=item *
 C<name> I<optional>

 The name of the file, this is automatically detected if uploading a file with a POST and multipart / form-data

=item *
 C<type> I<optional>

 The type of the file that's being sent; file, base64 or URL

=cut

=head2 delete

  Deletes an image. For an anonymous image, {id} must be the image's deletehash. If the image belongs to your account then passing the ID of the image is sufficient. 

B<Parameters>

=item *
 C<image> I<required>

 Image

=cut

=head2 update

  Updates the title or description of an image. You can only update an image you own and is associated with your account. For an anonymous image, {id} must be the image's deletehash. 

B<Parameters>

=item *
 C<description> I<optional>

 The description of the image.

=item *
 C<title> I<optional>

 The title of the image.

=item *
 C<image> I<required>

 Image

=cut

=head2 favorite

 Favorite an image with the given ID. The user is required to be logged in to favorite the image.

B<Parameters>

=item *
 C<image> I<required>

 Image

=cut


