=head1 NAME

 Imgur::API::Endpoint::Notification

=head1 DESCRIPTION

 Access to the imgur Notification API Endpoint. 

 See: https://api.imgur.com/endpoints/notification

=cut

=head1 METHODS
 
=head2 notifications

 Get all notifications for the user that's currently logged in

B<Parameters>

=item *
 C<new> I<optional>

 boolean - false for all notifications, true for only non-viewed notification. Default is true.

=cut

=head2 get

 Returns the data about a specific notification

B<Parameters>

=item *
 C<notification> I<required>

 Notification

=cut

=head2 viewed

 Marks a notification as viewed, this way it no longer shows up in the basic notification request

B<Parameters>

=item *
 C<ids> I<optional>

 To mark multiple notifications as read in one call, pass in an 'ids' parameter (omitting the 'id' parameter in the route) with the value of a comma-separated string of notification ids.

=item *
 C<notification> I<required>

 Notification

=cut


