=head1 NAME

 Imgur::API::Endpoint::Topic

=head1 DESCRIPTION

 Access to the imgur Topic API Endpoint. 

 See: https://api.imgur.com/endpoints/topic

=cut

=head1 METHODS
 
=head2 defaults

 Get the list of default topics.

B<Parameters>

=cut

=head2 galleryTopic

 View gallery items for a topic

B<Parameters>

=item *
 C<page> I<optional>

 integer - the data paging number

=item *
 C<topic_id> I<required>

 The ID or URL-formatted name of the topic. If using a topic's name, replace its spaces with underscores (Mother's_Day).

=item *
 C<window> I<optional>

 Change the date range of the request if the sort is "top", day | week | month | year | all, defaults to week

=item *
 C<sort> I<optional>

 viral | time | top - defaults to viral

=cut

=head2 galleryTopicItem

 View a single item in a gallery topic

B<Parameters>

=item *
 C<topic_id> I<required>

 The ID or URL-formatted name of the topic. If using a topic's name, replace its spaces with underscores (Mother's_Day).

=item *
 C<item_id> I<required>

 The ID for the gallery item.

=cut


